export type CommandEntrancePath = string;

/** Static CLI primary-path baseline captured from the assembled Commander program. */
export const CLI_ENTRANCE_BASELINE: readonly CommandEntrancePath[] = [
  "acp",
  "acp list",
  "acp login",
  "acp test",
  "acp usage",
  "ad",
  "agent",
  "agent dispatch",
  "agent-mission",
  "agent-mission capabilities",
  "agent-mission config-migrate",
  "agent-mission mission",
  "agent-mission models",
  "agent-mission review-loop",
  "agent-mission review-stats",
  "agent-mission review-watch",
  "agent-mission setup",
  "ask",
  "attach",
  "autopilot",
  "autopilot add-phase",
  "autopilot approve",
  "autopilot arm",
  "autopilot briefing",
  "autopilot cancel",
  "autopilot check",
  "autopilot decide",
  "autopilot decompose-crash",
  "autopilot decompose-stream",
  "autopilot delete-arc",
  "autopilot delete-phase",
  "autopilot escalate",
  "autopilot freshness",
  "autopilot history",
  "autopilot inject",
  "autopilot insert-arc",
  "autopilot insert-phase",
  "autopilot landing",
  "autopilot link",
  "autopilot list",
  "autopilot materialize",
  "autopilot maturity-split",
  "autopilot merge",
  "autopilot negotiate",
  "autopilot pause",
  "autopilot phases",
  "autopilot pipeline",
  "autopilot prepare-log",
  "autopilot promote",
  "autopilot rebuild",
  "autopilot reconcile",
  "autopilot redesign",
  "autopilot reorder-arc",
  "autopilot rereflect",
  "autopilot rerun",
  "autopilot resources",
  "autopilot restart-daemon",
  "autopilot resume",
  "autopilot review",
  "autopilot revise",
  "autopilot revise-suggest",
  "autopilot run",
  "autopilot signal",
  "autopilot skip",
  "autopilot split",
  "autopilot system-repair",
  "autopilot threads",
  "autopilot trace",
  "autopilot unlink",
  "ax-screen",
  "browser",
  "browser annotate",
  "browser chart",
  "browser clear",
  "buzz",
  "chat",
  "config",
  "config get",
  "config mission",
  "config mission get",
  "config mission mode",
  "config mission reset",
  "config mission set",
  "config path",
  "config promote",
  "config set",
  "config sync-test",
  "config unset",
  "connector",
  "connector linear",
  "connector linear receive",
  "connector linear set-key",
  "connector linear set-webhook-secret",
  "connector linear sync",
  "control",
  "control join",
  "control member",
  "control serve",
  "control token",
  "control token issue",
  "control token list",
  "control token revoke",
  "decide",
  "decide-recipe",
  "dev",
  "discord-test",
  "docs",
  "docs revision",
  "docs search",
  "docs stale",
  "doctor",
  "factcheck",
  "finance",
  "finance sector-flow",
  "fleet",
  "fleet list",
  "fleet screen",
  "gh",
  "git",
  "graph",
  "graph approve",
  "graph notify",
  "graph run",
  "graph status",
  "grounding",
  "grounding sources",
  "grounding sources add",
  "grounding sources discover",
  "grounding sources export",
  "grounding sources list",
  "grounding sources remove",
  "grounding sources status",
  "harness",
  "harness ask",
  "harness browser-act",
  "harness browser-type",
  "harness budget",
  "harness clean",
  "harness deliverable-verify",
  "harness dogfood",
  "harness drafts",
  "harness drafts sweep",
  "harness map",
  "harness mission",
  "harness orchestrate",
  "harness plan",
  "harness processes",
  "harness replay",
  "harness run",
  "harness run-detached",
  "harness say",
  "harness stop",
  "harness terminals-purge",
  "harness trajectory",
  "harness verify-url",
  "harness worktree",
  "harness worktree add",
  "harness worktrees",
  "history",
  "hooks",
  "hooks serve",
  "hooks status",
  "inspect",
  "intake",
  "intake check",
  "intake collect-github",
  "intake collect-pod",
  "intake collect-telegram-saved",
  "intake digest",
  "intake grounding-sync",
  "intake ingest",
  "intake items",
  "intake mark",
  "intake queue",
  "intake route",
  "intake to-tasks",
  "keys",
  "labels",
  "labels list",
  "labels sync",
  "launch-head",
  "launch-head balance",
  "launch-head capability",
  "leader",
  "leader claim",
  "leader status",
  "local",
  "local bench",
  "local chat",
  "local inventory",
  "local models",
  "local pick",
  "local ping",
  "local scores",
  "local setup",
  "local test",
  "login",
  "login logout",
  "login openai-codex",
  "login status",
  "logs",
  "logs abandoned-draft-prs",
  "logs degenerate",
  "logs durations",
  "logs fields",
  "logs instances",
  "logs level",
  "logs timeline",
  "logs unclosed",
  "loops",
  "machine",
  "machine set",
  "machine show",
  "mcp",
  "mcp call",
  "mcp diagnose",
  "mcp list",
  "mcp login",
  "mcp reload",
  "mcp serve",
  "measure-fabric-arc-ab",
  "memory",
  "memory add",
  "memory delete",
  "memory index",
  "memory list",
  "memory pin",
  "memory priority",
  "memory search",
  "memory show",
  "memory status",
  "memory unpin",
  "memory where",
  "model-watch",
  "model-watch apply",
  "nexus",
  "nexus build",
  "nexus channel-bot",
  "nexus channel-bot setup",
  "nexus config",
  "nexus config get",
  "nexus config list",
  "nexus config set",
  "nexus config unset",
  "nexus connect",
  "nexus dist",
  "nexus dist link",
  "nexus dist publish",
  "nexus ingest-token",
  "nexus ingest-token issue",
  "nexus ingest-token list",
  "nexus ingest-token revoke",
  "nexus install",
  "nexus ios-bind",
  "nexus list",
  "nexus pwa",
  "nexus pwa build",
  "nexus pwa dev",
  "nexus pwa global",
  "nexus pwa global clean",
  "nexus pwa global status",
  "nexus pwa restart",
  "nexus pwa share",
  "nexus pwa share disable",
  "nexus pwa share enable",
  "nexus pwa share status",
  "nexus pwa show",
  "nexus pwa start",
  "nexus pwa stop",
  "nexus pwa verify",
  "nexus remove",
  "nexus restart-needed",
  "nexus run",
  "nexus setup-firecrawl",
  "nexus show",
  "nexus status",
  "nexus stop",
  "nexus switch",
  "nexus uninstall",
  "onboarding",
  "ops",
  "ops build",
  "ops health",
  "ops mission",
  "ops mission-log",
  "ops status",
  "ops timeline",
  "pod",
  "pod run",
  "pr",
  "pr granularity",
  "pr land",
  "provider",
  "provider codex",
  "provider codex account",
  "provider codex account import",
  "provider codex account list",
  "provider codex reset-credits",
  "provider codex reset-credits list",
  "provider codex reset-credits observe",
  "provider codex reset-credits redeem",
  "provider codex status",
  "provider codex usage",
  "provider:restore",
  "provider:rotate",
  "provider:set",
  "provider:use",
  "pty",
  "pty auto",
  "pty find",
  "pty key",
  "pty lineage",
  "pty list",
  "pty reap",
  "pty release",
  "pty resize",
  "pty retire",
  "pty snapshot",
  "pty state",
  "pty takeover",
  "pty text",
  "pty wait",
  "publish",
  "publish catalog",
  "publish file",
  "publish gc",
  "python",
  "python check",
  "python setup",
  "python where",
  "questions",
  "questions answer",
  "questions pending",
  "registry",
  "registry discover",
  "registry drift",
  "release",
  "release notes",
  "release prepare",
  "release publish",
  "release tag",
  "release verify",
  "release yank",
  "repl",
  "repo",
  "repo design-archive",
  "repo design-check",
  "repo design-css",
  "repo design-direction",
  "repo design-extract",
  "repo design-lint",
  "repo design-screen-contrast",
  "repo public",
  "repo publish",
  "repo scaffold",
  "repo webclone-judge",
  "repro",
  "resources",
  "resources list",
  "resources where",
  "role",
  "role accept",
  "role claim",
  "role handoff",
  "role set-machine",
  "role status",
  "role watch",
  "role whoami",
  "schedule",
  "schedule adopt",
  "schedule create",
  "schedule delete",
  "schedule disable",
  "schedule enable",
  "schedule inspect",
  "schedule list",
  "schedule migrate",
  "schedule release",
  "schedule retarget",
  "schedule unwrap",
  "schedule update",
  "schedule wrap",
  "scheduler",
  "self",
  "self author",
  "self capabilities",
  "self capability",
  "self clarify",
  "self clarify answer",
  "self clarify closure",
  "self clarify list",
  "self clarify pending",
  "self entrances",
  "self gate",
  "self git-discipline",
  "self goal-asks",
  "self goal-run",
  "self goal-run-search",
  "self goal-runs",
  "self goal-source-distribution",
  "self goal-status",
  "self goal-test-scenarios",
  "self implement",
  "self ledger",
  "self ledger compact",
  "self ledger lint",
  "self log",
  "self merge-attribution",
  "self orchestrate",
  "self orphan-sweep",
  "self parked",
  "self participants",
  "self provision",
  "self recall",
  "self reduce",
  "self repair-signals",
  "self review",
  "self run",
  "self run-chain",
  "self run-ledger",
  "self running-runs",
  "self screen",
  "self send",
  "self typecheck",
  "self unfinished-runs",
  "self unfinished-runs-cleanup",
  "self utterance",
  "self-update",
  "session",
  "session compact",
  "session context",
  "session delete",
  "session export",
  "session fork",
  "session link",
  "session list",
  "session new",
  "session open",
  "session purge",
  "session release",
  "session resume",
  "session search",
  "session show",
  "session subscribe",
  "session subscribers",
  "session takeover",
  "session turn",
  "session unsubscribe",
  "session watch",
  "setup",
  "shadow",
  "shadow diff",
  "shadow log",
  "shadow restore",
  "shadow snapshot",
  "signals",
  "status",
  "status-bar",
  "sync",
  "tasks",
  "tasks approve",
  "tasks list",
  "tasks show",
  "telegram",
  "telegram run",
  "telegram service",
  "telegram-test",
  "theme",
  "theme export",
  "theme list",
  "theme preview",
  "theme use",
  "tier",
  "tier list",
  "tier providers",
  "tier resolve",
  "token",
  "token rotate",
  "usage",
  "usage reset",
  "usage runs",
  "voice",
  "voice nl-switch",
  "voice status",
  "voice suggest",
  "wf",
  "wf list",
  "wf node",
  "wf node list",
  "wf node search",
  "wf node spec",
  "wf run",
  "wf show",
  "wf suggest-next",
  "wf synth",
  "wf validate",
  "where",
];

export interface EntranceBaselineComparison {
  missing: CommandEntrancePath[];
  added: CommandEntrancePath[];
}

export interface EntranceBaselineEvaluation extends EntranceBaselineComparison {
  exitCode: 0 | 1;
}

/**
 * Compares an externally supplied baseline with Commander-tree entrances.
 * Missing baseline paths are regressions; added paths remain visible but pass.
 */
export function compareCommandEntranceBaseline(
  baseline: readonly CommandEntrancePath[],
  actualEntrances: readonly { path: readonly string[] }[],
): EntranceBaselineComparison {
  const actual = new Set(actualEntrances.map((entrance) => entrance.path.join(' ')));
  const expected = new Set(baseline);
  return {
    missing: [...expected].filter((path) => !actual.has(path)),
    added: [...actual].filter((path) => !expected.has(path)),
  };
}

/** Returns the command status derived from a supplied, static baseline comparison. */
export function evaluateCommandEntranceBaseline(
  baseline: readonly CommandEntrancePath[],
  actualEntrances: readonly { path: readonly string[] }[],
): EntranceBaselineEvaluation {
  const comparison = compareCommandEntranceBaseline(baseline, actualEntrances);
  return { ...comparison, exitCode: comparison.missing.length === 0 ? 0 : 1 };
}
